### PR TITLE
LLNL Workshop Website Draft

### PR DESCRIPTION
**Pull request by wadawson**
For the meantime I decide to keep the same path/format for the LLNL workshop out of ease, but please let me know if you think we should do something different. I could alternatively host the website from LLNL. 

I moved the Pitt meeting to a new page in Previous Workshops.

### CODE REVIEW

**Comment by yymao** [comment]
Looks good. I would put the bullet points under the "previously workshop" page directly in the main page, just like other sections. 

And maybe consider change the banner image? So that the new website would be more visually different?

**Comment by kadrlica** [comment]
I agree with Yao that this looks very nice, and that a banner change would be a good idea.

I think that the plan is to have a more open registration, so we probably want to add a "Registration" section. For right now we can put "Coming soon", but at some point we should add a link to a google form or indico registration page.

**Comment by wadawson** [comment]
I agree with the suggestions. I will work on implementing them tonight. Thanks.

**Comment by kadrlica** [comment]
@wadawson I used an image of the Musket Ball cluster that you were credited with under the assumption that no one would complain about it's reuse. Please correct me if I'm wrong.

**Comment by kadrlica** [comment]
@yymao Leaving `previous_workshops.html` was actually intentional. If we continue to have these workshops I think that having a separate page will be useful later on. Is there a strong motivation to remove it?

**Comment by yymao** [comment]
It was a design choice to do single page. If we are having more than one page, we should (1) consider use a static site generator so that we are not copying and pasting the overall format/style in each page and (2) change the navigation menu style to distinguish links within page and cross page. I'd say we can worry about these when we really need a second page. How does that sound?

**Comment by kadrlica** [comment]
Sounds good, thanks.

**Comment by wadawson** [comment]
@kadrlica, Looks great! Thank you for making the changes.

**Pull request merged**
