### PR TITLE
Agenda

### PR DESCRIPTION
**Pull request by kadrlica**
I've added a separate html page with a preliminary agenda. @yymao can you let me know if this conforms with your vision of the page structure? We could also potentially have this included in `index.html` (or have a separate google doc with the agenda). All thoughts and suggestions are welcome.

### CODE REVIEW

**Comment by yymao** [comment]
@kadrlica The agenda seem light enough to be included just in `index.html`? I like things to be in one place unless it's really too big.

**Comment by kadrlica** [comment]
Ok, I'll make the changes and re-commit.

**Comment by kadrlica** [comment]
@yymao I've put everything into `index.html` and removed `agenda.html`. Ready for review/merge.

**Comment by yymao** [comment]
added color to agenda. made agenda and participants responsive. removed some texts in the beginning.

**Comment by yymao** [comment]
@kadrlica your edit breaks the alignment in my browser. Do you see something different?  

image

**Comment by kadrlica** [comment]
I've attached what the current alignment looks like on my browser. It is not perfect, but the previous alignment was completely mis-matched for me.

image

**Comment by kadrlica** [comment]
@yymao could it be due to differences in font sizes between our browsers? (I think I have mine set larger than default.)

**Comment by yymao** [comment]
Yep, that's due to font size... Let me think if there's an easy solution...

**Comment by kadrlica** [comment]
Hmm, not sure that helped a ton (see below), but I don't think we need perfection on this. I'm happy to accept these changes.

image

**Comment by yymao** [comment]
OK --- this should (hopefully) work now. @kadrlica

**Comment by kadrlica** [comment]
@yymao I confirm that works for me.

**Pull request merged**
